# -*- coding: utf-8 -*-
"""Study Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pi5HN8jR183CffstLbIm54ftodRC9aIn
"""

!pip install openai python-dotenv

"""# Set Environment Variables"""

from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

import os

os.environ["MODEL_NAME"] = "gpt-4o-mini"
os.environ["TEMPERATURE"] = "0.3"
os.environ["MAX_TOKENS"] = "800"

import os

print("API key loaded:", os.environ.get("OPENAI_API_KEY") is not None)
print("Model:", os.environ.get("MODEL_NAME"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config.py
# import os
# 
# MODEL_NAME = os.getenv("MODEL_NAME")
# TEMPERATURE = float(os.getenv("TEMPERATURE"))
# MAX_TOKENS = int(os.getenv("MAX_TOKENS"))
#

"""# Create Provider Layer
Base Provider
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile base_provider.py
# from abc import ABC, abstractmethod
# 
# class BaseProvider(ABC):
# 
#     @abstractmethod
#     def generate(self, prompt: str):
#         pass
#

"""# OpenAI Provider"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile openai_provider.py
# from openai import OpenAI
# from config import MODEL_NAME, TEMPERATURE, MAX_TOKENS
# 
# class OpenAIProvider:
#     def __init__(self):
#         self.client = OpenAI()
# 
#     def generate(self, prompt: str):
#         response = self.client.chat.completions.create(
#             model=MODEL_NAME,
#             messages=[{"role": "user", "content": prompt}],
#             temperature=TEMPERATURE,
#             max_tokens=MAX_TOKENS
#         )
#         return response.choices[0].message.content
#

"""# Prompt Functions
Flashcard Prompt
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile flashcard_prompt.py
# def flashcard_prompt(text):
#     return f"""
# Generate flashcards.
# 
# Return JSON only.
# 
# Format:
# [
#   {{
#     "question": "...",
#     "answer": "..."
#   }}
# ]
# 
# Text:
# {text}
# """
#

"""# Quiz Prompt"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile quiz_prompt.py
# def quiz_prompt(text):
#     return f"""
# Generate MCQ questions.
# 
# Return JSON only.
# 
# Format:
# [
#   {{
#     "question": "...",
#     "options": ["A","B","C","D"],
#     "correct_answer": "A"
#   }}
# ]
# 
# Text:
# {text}
# """
#

"""# Summary Prompt"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile summary_prompt.py
# def summary_prompt(text):
#     return f"""
# Summarize the text clearly.
# 
# Text:
# {text}
# """
#

"""# Evaluation Prompt"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile evaluation_prompt.py
# def evaluation_prompt(correct, user):
#     return f"""
# Evaluate the answer.
# 
# Correct:
# {correct}
# 
# User:
# {user}
# 
# Return JSON:
# {{
#   "score": 0-100,
#   "feedback": "short feedback"
# }}
# """
#

"""# AI Engines
Flashcard Engine
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile flashcard_engine.py
# from flashcard_prompt import flashcard_prompt
# 
# class FlashcardEngine:
#     def __init__(self, provider):
#         self.provider = provider
# 
#     def generate(self, text):
#         return self.provider.generate(flashcard_prompt(text))
#

"""# Quiz Engine"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile quiz_engine.py
# from quiz_prompt import quiz_prompt
# 
# class QuizEngine:
#     def __init__(self, provider):
#         self.provider = provider
# 
#     def generate(self, text):
#         return self.provider.generate(quiz_prompt(text))
#

"""# Summary Engine"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile summary_engine.py
# from summary_prompt import summary_prompt
# 
# class SummaryEngine:
#     def __init__(self, provider):
#         self.provider = provider
# 
#     def generate(self, text):
#         return self.provider.generate(summary_prompt(text))
#

"""# Evaluation Engine"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile evaluation_engine.py
# from evaluation_prompt import evaluation_prompt
# 
# class EvaluationEngine:
#     def __init__(self, provider):
#         self.provider = provider
# 
#     def evaluate(self, correct, user):
#         return self.provider.generate(evaluation_prompt(correct, user))
#

"""# Test Everything MAIN CELL"""

import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

from openai_provider import OpenAIProvider
from flashcard_engine import FlashcardEngine
from quiz_engine import QuizEngine
from summary_engine import SummaryEngine
from evaluation_engine import EvaluationEngine

provider = OpenAIProvider()

text = """
Machine learning is a subset of artificial intelligence
that enables systems to learn from data.
"""

print("FLASHCARDS:")
print(FlashcardEngine(provider).generate(text))

print("\nQUIZ:")
print(QuizEngine(provider).generate(text))

print("\nSUMMARY:")
print(SummaryEngine(provider).generate(text))

print("\nEVALUATION:")
print(EvaluationEngine(provider).evaluate(
    "ML allows systems to learn from data",
    "ML learns automatically"
))